### ISSUE TITLE
v0.19 breaks container methods

### ISSUE THREAD

**Issue by edgarjs** [dry-rb/dry-system#174]
## Describe the bug

Here's my container which works fine on v0.18.1:

```ruby
# frozen_string_literal: true

require 'dry/system/container'

class App < Dry::System::Container
  use :env, inferrer: -> { ENV['RACK_ENV'].to_sym }
  use :logging

  configure do |config|
    config.logger = Logger.new($stdout)

    config.auto_register = %w[
      lib/report_service/services/persistence/repos
      lib/report_service/operations
      lib/report_service/workflows
    ]
  end

  load_paths!('lib', 'system')
end
```

However I just tried to update to 0.19 but when booting up it throws this error:

```sh
...gems/dry-configurable-0.12.1/lib/dry/configurable/config.rb:106:in `method_missing': undefined method `auto_register=' for #<Dry::Configurable::Config:0x00007f823e24be00> (NoMethodError)
```

And I try to comment the `config.auto_register=` lines, it then breaks with:

```sh
...system/container.rb:19:in `<class:App>': undefined method `load_paths!' for App:Class (NoMethodError)
```

## To Reproduce

Update from 0.18.1 to 0.19.

## Expected behavior

I would expect the container to boot up.

## My environment

- Affects my production application: **I'm not deploying this**
- Ruby version: 2.6.5
- OS: macos 10.15.7

**Comment by flash-gordon** [comment]
Have you read the [changelogs](https://github.com/dry-rb/dry-system/blob/master/CHANGELOG.md#0190-2021-04-22) though? :)

**Comment by edgarjs** [comment]
Oh! my bad. Thank you for pointing it out.
